#!/usr/bin/env bash
source /etc/backup/discord.conf

DATA="{\"username\": \"$USER\", \"content\":  \"**@everyone notification from <t:$( date +"%s" ):F>**\n\`\`\`$( systemctl status --full $1 | sed ':a;N;$!ba;s/\n/ /g' | sed 's/"/\\"/' )\`\`\`\"}"

echo "$DATA"
curl -H 'Content-Type:application/json' \
	-d "$DATA" \
    "$( cat $WEBHOOK_FILE )"
