#!/usr/bin/env bash
source /etc/backup/discord.conf

if [[ $1 = 'meta:confirmation' ]]; then
	DATA="{\"username\": \"$USER\", \"content\":  \"backup script successfully initialized!\"}"
else
	REPORT=$( systemctl status --full $1 | sed ':a;N;$!ba;s/\n/ /g' | sed 's/"/\\"/' )
	TIME=$(date +"%s")
	DATA="{\"username\": \"$USER\", \"content\":  \"**@everyone notification from <t:$TIME:F>**\n\`\`\`$REPORT\`\`\`\"}"
fi

curl -H 'Content-Type:application/json' \
	-d "$DATA" 							\
    "$( cat $WEBHOOK_FILE )"
